//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJUSTE
    {
        public int id { get; set; }
        public Nullable<int> minimoAreia { get; set; }
        public Nullable<int> minimoBrita0 { get; set; }
        public Nullable<int> minimoBrita1 { get; set; }
        public Nullable<int> minimoCimento { get; set; }
        public Nullable<int> minimoaditivo { get; set; }
        public Nullable<int> tempoAreia { get; set; }
        public Nullable<int> tempoBrita0 { get; set; }
        public Nullable<int> tempoBrita1 { get; set; }
        public Nullable<int> tempoCimento { get; set; }
        public Nullable<int> tempoAditivo { get; set; }
        public Nullable<int> tempoAgua { get; set; }
        public Nullable<System.DateTime> dataAjuste { get; set; }
    }
}
