//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTOQUE
    {
        public int ID { get; set; }
        public double Agr1Est { get; set; }
        public double Agr2Est { get; set; }
        public double Agr3Est { get; set; }
        public double Cim1Est { get; set; }
        public double Adit1Est { get; set; }
    }
}
