//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PRODUCAO = new HashSet<PRODUCAO>();
        }
    
        public int ID { get; set; }
        public int IDCliente { get; set; }
        public int IDCaminhao { get; set; }
        public int IDColaborador { get; set; }
        public int IDReceita { get; set; }
        public Nullable<int> IDOperaçao { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<double> PesagemCaminhao { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<bool> Controle { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COLABORADOR COLABORADOR { get; set; }
        public virtual RECEITA RECEITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCAO> PRODUCAO { get; set; }
        public virtual FROTA FROTA { get; set; }
    }
}
