//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCAO
    {
        public int ID { get; set; }
        public int IDPedido { get; set; }
        public Nullable<System.DateTime> DataProducao { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<double> Agr1Real { get; set; }
        public Nullable<double> Agr1Prog { get; set; }
        public Nullable<double> Agr2Real { get; set; }
        public Nullable<double> Agr2Prog { get; set; }
        public Nullable<double> Agr3Real { get; set; }
        public Nullable<double> Agr3Prog { get; set; }
        public Nullable<double> CimReal { get; set; }
        public Nullable<double> CimProg { get; set; }
        public Nullable<double> AguaReal { get; set; }
        public Nullable<double> AguaProg { get; set; }
        public Nullable<double> AditReal { get; set; }
        public Nullable<double> AditProg { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
