//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEITA()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<double> Agr1Prog { get; set; }
        public Nullable<double> Agr2Prog { get; set; }
        public Nullable<double> Agr3Prog { get; set; }
        public Nullable<double> Cim1Prog { get; set; }
        public Nullable<double> Agua1Prog { get; set; }
        public Nullable<double> Adit1Prog { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
