//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassMark2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aula()
        {
            this.Presenca = new HashSet<Presenca>();
        }
    
        public int ID { get; set; }
        public int IDMateria { get; set; }
        public System.DateTime DataAula { get; set; }
        public System.TimeSpan HorarioInicio { get; set; }
        public System.TimeSpan HorarioFim { get; set; }
        public byte[] QRCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presenca> Presenca { get; set; }
    }
}
