//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassMark2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public int IDCurso { get; set; }
        public int AnoCurso { get; set; }
        public int IDProfessor { get; set; }
        public string Descricao { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
