//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassMark2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomeProfessor
    {
        public string Nome { get; set; }
        public string Curso { get; set; }
        public System.DateTime DataInicio { get; set; }
        public int Duracao { get; set; }
        public string TipoCurso { get; set; }
        public int ID { get; set; }
    }
}
