//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassMark2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presenca
    {
        public int ID { get; set; }
        public int IDAluno { get; set; }
        public int IDAula { get; set; }
        public string StatusPresenca { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Aula Aula { get; set; }
    }
}
